// ─────────────────────────────────────────────────────────
// GERADO por scripts/gen-poco.mjs — não editar à mão.
//
// Índice das peças do criador de personagem de O POÇO. O rótulo sai
// do nome do arquivo original, traduzido palavra por palavra pelo
// dicionário do gerador.
// ─────────────────────────────────────────────────────────

export interface PecaCatalogo { id: string; rotulo: string }
export type Sexo = 'm' | 'f';
export type Camada = 'corpo' | 'orelha' | 'cabelo' | 'roupa' | 'braco' | 'chapeu' | 'mascara' | 'mao' | 'amarras';

export const CATALOGO: Record<Camada, Record<Sexo, PecaCatalogo[]>> = {
  corpo: {
    m: [
      { id: 'male-skin-1.png', rotulo: "Pele 1" },
      { id: 'male-skin-2.png', rotulo: "Pele 2" },
      { id: 'male-skin-3.png', rotulo: "Pele 3" },
      { id: 'male-skin-4.png', rotulo: "Pele 4" },
      { id: 'male-skin-5.png', rotulo: "Pele 5" },
      { id: 'male-demon-skin.png', rotulo: "Pele de demônio" },
      { id: 'male-devil-skin.png', rotulo: "Pele de diabo" },
      { id: 'male-ghost-skin.png', rotulo: "Pele de fantasma" },
      { id: 'male-orc-skin.png', rotulo: "Pele de orc" },
      { id: 'male-zombie-skin.png', rotulo: "Pele de zumbi" },
    ],
    f: [
      { id: 'female-skin-1.png', rotulo: "Pele 1" },
      { id: 'female-skin-2.png', rotulo: "Pele 2" },
      { id: 'female-skin-3.png', rotulo: "Pele 3" },
      { id: 'female-skin-4.png', rotulo: "Pele 4" },
      { id: 'female-skin-5.png', rotulo: "Pele 5" },
      { id: 'female-demon-skin.png', rotulo: "Pele de demônio" },
      { id: 'female-devil-skin.png', rotulo: "Pele de diabo" },
      { id: 'female-ghost-skin.png', rotulo: "Pele de fantasma" },
      { id: 'female-orc-skin.png', rotulo: "Pele de orc" },
      { id: 'female-zombie-skin.png', rotulo: "Pele de zumbi" },
    ],
  },
  orelha: {
    m: [
      { id: 'elven-ears-1.png', rotulo: "Orelhas élficas 1" },
      { id: 'elven-ears-2.png', rotulo: "Orelhas élficas 2" },
      { id: 'elven-ears-3.png', rotulo: "Orelhas élficas 3" },
      { id: 'elven-ears-4.png', rotulo: "Orelhas élficas 4" },
      { id: 'elven-ears-5.png', rotulo: "Orelhas élficas 5" },
    ],
    f: [
      { id: 'elven-ears-1.png', rotulo: "Orelhas élficas 1" },
      { id: 'elven-ears-2.png', rotulo: "Orelhas élficas 2" },
      { id: 'elven-ears-3.png', rotulo: "Orelhas élficas 3" },
      { id: 'elven-ears-4.png', rotulo: "Orelhas élficas 4" },
      { id: 'elven-ears-5.png', rotulo: "Orelhas élficas 5" },
    ],
  },
  cabelo: {
    m: [
      { id: 'male-hair-1.png', rotulo: "Cabelo 1" },
      { id: 'male-hair-2.png', rotulo: "Cabelo 2" },
      { id: 'male-hair-3.png', rotulo: "Cabelo 3" },
      { id: 'male-hair-4.png', rotulo: "Cabelo 4" },
      { id: 'male-hair-5.png', rotulo: "Cabelo 5" },
      { id: 'fancy-hair.png', rotulo: "Cabelo de gala" },
      { id: 'male-hair-6.png', rotulo: "Cabelo 6" },
      { id: 'male-hair-7.png', rotulo: "Cabelo 7" },
      { id: 'male-hair-8.png', rotulo: "Cabelo 8" },
      { id: 'male-hair-9.png', rotulo: "Cabelo 9" },
      { id: 'male-hair-10.png', rotulo: "Cabelo 10" },
      { id: 'male-hair-11.png', rotulo: "Cabelo 11" },
      { id: 'male-hair-12.png', rotulo: "Cabelo 12" },
      { id: 'male-hair-13.png', rotulo: "Cabelo 13" },
      { id: 'male-hair-14.png', rotulo: "Cabelo 14" },
      { id: 'male-hair-15.png', rotulo: "Cabelo 15" },
      { id: 'male-hair-16.png', rotulo: "Cabelo 16" },
      { id: 'male-hair-17.png', rotulo: "Cabelo 17" },
      { id: 'male-hair-18.png', rotulo: "Cabelo 18" },
      { id: 'male-hair-19.png', rotulo: "Cabelo 19" },
      { id: 'male-hair-20.png', rotulo: "Cabelo 20" },
      { id: 'male-hair-21.png', rotulo: "Cabelo 21" },
      { id: 'male-hair-22.png', rotulo: "Cabelo 22" },
      { id: 'male-hair-23.png', rotulo: "Cabelo 23" },
      { id: 'male-hair-24.png', rotulo: "Cabelo 24" },
      { id: 'male-hair-25.png', rotulo: "Cabelo 25" },
      { id: 'male-hair-26.png', rotulo: "Cabelo 26" },
      { id: 'male-hair-27.png', rotulo: "Cabelo 27" },
      { id: 'male-hair-28.png', rotulo: "Cabelo 28" },
      { id: 'male-hair-29.png', rotulo: "Cabelo 29" },
      { id: 'male-hair-30.png', rotulo: "Cabelo 30" },
      { id: 'queen-hair.png', rotulo: "Cabelo de rainha" },
      { id: 'shield-maiden-hair.png', rotulo: "Cabelo de escudeira" },
    ],
    f: [
      { id: 'female-hair-1.png', rotulo: "Cabelo 1" },
      { id: 'female-hair-2.png', rotulo: "Cabelo 2" },
      { id: 'female-hair-3.png', rotulo: "Cabelo 3" },
      { id: 'female-hair-4.png', rotulo: "Cabelo 4" },
      { id: 'female-hair-5.png', rotulo: "Cabelo 5" },
      { id: 'female-hair-6.png', rotulo: "Cabelo 6" },
      { id: 'female-hair-7.png', rotulo: "Cabelo 7" },
      { id: 'female-hair-8.png', rotulo: "Cabelo 8" },
      { id: 'female-hair-9.png', rotulo: "Cabelo 9" },
      { id: 'female-hair-10.png', rotulo: "Cabelo 10" },
      { id: 'female-hair-11.png', rotulo: "Cabelo 11" },
      { id: 'female-hair-12.png', rotulo: "Cabelo 12" },
      { id: 'female-hair-13.png', rotulo: "Cabelo 13" },
      { id: 'female-hair-14.png', rotulo: "Cabelo 14" },
      { id: 'female-hair-15.png', rotulo: "Cabelo 15" },
      { id: 'female-hair-16.png', rotulo: "Cabelo 16" },
      { id: 'female-hair-17.png', rotulo: "Cabelo 17" },
      { id: 'female-hair-18.png', rotulo: "Cabelo 18" },
      { id: 'female-hair-19.png', rotulo: "Cabelo 19" },
      { id: 'female-hair-20.png', rotulo: "Cabelo 20" },
      { id: 'female-hair-21.png', rotulo: "Cabelo 21" },
      { id: 'female-hair-22.png', rotulo: "Cabelo 22" },
      { id: 'female-hair-23.png', rotulo: "Cabelo 23" },
      { id: 'female-hair-24.png', rotulo: "Cabelo 24" },
      { id: 'female-hair-25.png', rotulo: "Cabelo 25" },
      { id: 'female-hair-26.png', rotulo: "Cabelo 26" },
      { id: 'female-hair-27.png', rotulo: "Cabelo 27" },
      { id: 'female-hair-28.png', rotulo: "Cabelo 28" },
      { id: 'female-hair-29.png', rotulo: "Cabelo 29" },
      { id: 'female-hair-30.png', rotulo: "Cabelo 30" },
      { id: 'female-hair-31.png', rotulo: "Cabelo 31" },
      { id: 'female-hair-32.png', rotulo: "Cabelo 32" },
      { id: 'female-hair-33.png', rotulo: "Cabelo 33" },
      { id: 'female-hair-34.png', rotulo: "Cabelo 34" },
      { id: 'female-hair-35.png', rotulo: "Cabelo 35" },
    ],
  },
  roupa: {
    m: [
      { id: 'blue-pants.png', rotulo: "Calça azul" },
      { id: 'blue-shirt-v-2.png', rotulo: "Camisa II azul" },
      { id: 'boots.png', rotulo: "Botas" },
      { id: 'green-pants.png', rotulo: "Calça verde" },
      { id: 'green-shirt-v-2.png', rotulo: "Camisa II verde" },
      { id: 'orange-pants.png', rotulo: "Calça laranja" },
      { id: 'orange-shirt-v-2.png', rotulo: "Camisa II laranja" },
      { id: 'pants.png', rotulo: "Calça" },
      { id: 'purple-pants.png', rotulo: "Calça roxa" },
      { id: 'purple-shirt-v-2.png', rotulo: "Camisa II roxa" },
      { id: 'shirt-v-2.png', rotulo: "Camisa II" },
      { id: 'shirt.png', rotulo: "Camisa" },
      { id: 'shoes.png', rotulo: "Sapatos" },
      { id: 'chainmail.png', rotulo: "Cota de malha" },
      { id: 'split-hose.png', rotulo: "Calção bicolor" },
    ],
    f: [
      { id: 'blue-corset-v-2.png', rotulo: "Corpete II azul" },
      { id: 'blue-corset.png', rotulo: "Corpete azul" },
      { id: 'boots.png', rotulo: "Botas" },
      { id: 'corset-v-2.png', rotulo: "Corpete II" },
      { id: 'corset.png', rotulo: "Corpete" },
      { id: 'green-corset-v-2.png', rotulo: "Corpete II verde" },
      { id: 'green-corset.png', rotulo: "Corpete verde" },
      { id: 'green-socks.png', rotulo: "Meias verdes" },
      { id: 'orange-corset-v-2.png', rotulo: "Corpete II laranja" },
      { id: 'orange-corset.png', rotulo: "Corpete laranja" },
      { id: 'orange-socks.png', rotulo: "Meias laranja" },
      { id: 'purple-corset-v-2.png', rotulo: "Corpete II roxo" },
      { id: 'purple-corset.png', rotulo: "Corpete roxo" },
      { id: 'purple-socks.png', rotulo: "Meias roxas" },
      { id: 'red-socks.png', rotulo: "Meias vermelhas" },
      { id: 'skirt.png', rotulo: "Saia" },
      { id: 'skyblue-socks.png', rotulo: "Meias celestes" },
      { id: 'socks.png', rotulo: "Meias" },
      { id: 'armored-corset.png', rotulo: "Corpete de placas" },
      { id: 'black-thigh-high-boots.png', rotulo: "Botas de cano alto pretas" },
      { id: 'blue-bodice-long-sleeves.png', rotulo: "Colete de manga longa azul" },
      { id: 'blue-bodice-mid-sleeves.png', rotulo: "Colete de manga média azul" },
      { id: 'blue-bodice.png', rotulo: "Colete azul" },
      { id: 'blue-corset-long-sleeves.png', rotulo: "Corpete de manga longa azul" },
      { id: 'blue-corset-v-2-long-sleeves.png', rotulo: "Corpete II de manga longa azul" },
      { id: 'blue-dress.png', rotulo: "Vestido azul" },
      { id: 'brown-thigh-high-boots.png', rotulo: "Botas de cano alto marrons" },
      { id: 'corset-long-sleeves.png', rotulo: "Corpete de manga longa" },
      { id: 'corset-v-2-long-sleeves.png', rotulo: "Corpete II de manga longa" },
      { id: 'fancy-blue-dress.png', rotulo: "Vestido de gala azul" },
      { id: 'green-bodice-long-sleeves.png', rotulo: "Colete de manga longa verde" },
      { id: 'green-bodice-mid-sleeves.png', rotulo: "Colete de manga média verde" },
      { id: 'green-bodice.png', rotulo: "Colete verde" },
      { id: 'green-corset-long-sleeves.png', rotulo: "Corpete de manga longa verde" },
      { id: 'green-corset-v-2-long-sleeves.png', rotulo: "Corpete II de manga longa verde" },
      { id: 'long-dress-blue.png', rotulo: "Vestido longo azul" },
      { id: 'long-dress-green.png', rotulo: "Vestido longo verde" },
      { id: 'long-dress-orange.png', rotulo: "Vestido longo laranja" },
      { id: 'long-dress-purple.png', rotulo: "Vestido longo roxo" },
      { id: 'long-dress-red.png', rotulo: "Vestido longo vermelho" },
      { id: 'orange-bodice-long-sleeves.png', rotulo: "Colete de manga longa laranja" },
      { id: 'orange-bodice-mid-sleeves.png', rotulo: "Colete de manga média laranja" },
      { id: 'orange-bodice.png', rotulo: "Colete laranja" },
      { id: 'orange-corset-long-sleeves.png', rotulo: "Corpete de manga longa laranja" },
      { id: 'orange-corset-v-2-long-sleeves.png', rotulo: "Corpete II de manga longa laranja" },
      { id: 'pink-thigh-high-boots.png', rotulo: "Botas de cano alto rosa" },
      { id: 'purple-bodice-long-sleeves.png', rotulo: "Colete de manga longa roxo" },
      { id: 'purple-bodice-mid-sleeves.png', rotulo: "Colete de manga média roxo" },
      { id: 'purple-bodice.png', rotulo: "Colete roxo" },
      { id: 'purple-corset-long-sleeves.png', rotulo: "Corpete de manga longa roxo" },
      { id: 'purple-corset-v-2-long-sleeves.png', rotulo: "Corpete II de manga longa roxo" },
      { id: 'queen-dress.png', rotulo: "Vestido de rainha" },
      { id: 'red-bodice-long-sleeves.png', rotulo: "Colete de manga longa vermelho" },
      { id: 'red-bodice-mid-sleeves.png', rotulo: "Colete de manga média vermelho" },
      { id: 'red-bodice.png', rotulo: "Colete vermelho" },
      { id: 'red-thigh-high-boots.png', rotulo: "Botas de cano alto vermelhas" },
      { id: 'short-skirt.png', rotulo: "Saia curta" },
    ],
  },
  braco: {
    m: [
      { id: 'glove-blue.png', rotulo: "Luva azul" },
      { id: 'glove-green.png', rotulo: "Luva verde" },
      { id: 'glove-orange.png', rotulo: "Luva laranja" },
      { id: 'glove-purple.png', rotulo: "Luva roxa" },
      { id: 'glove-red.png', rotulo: "Luva vermelha" },
      { id: 'glove-white.png', rotulo: "Luva branca" },
      { id: 'gloves.png', rotulo: "Luvas" },
    ],
    f: [
      { id: 'opera-gloves-blue.png', rotulo: "Luvas de baile azuis" },
      { id: 'opera-gloves-brown.png', rotulo: "Luvas de baile marrons" },
      { id: 'opera-gloves-green.png', rotulo: "Luvas de baile verdes" },
      { id: 'opera-gloves-orange.png', rotulo: "Luvas de baile laranja" },
      { id: 'opera-gloves-purple.png', rotulo: "Luvas de baile roxas" },
      { id: 'opera-gloves-red.png', rotulo: "Luvas de baile vermelhas" },
      { id: 'opera-gloves.png', rotulo: "Luvas de baile" },
    ],
  },
  chapeu: {
    m: [
      { id: 'farming-hat-m.png', rotulo: "Chapéu de palha" },
      { id: 'guard-helmet.png', rotulo: "Elmo de guarda" },
      { id: 'male-blue-cap.png', rotulo: "Boné azul" },
      { id: 'male-green-cap.png', rotulo: "Boné verde" },
      { id: 'male-hat-1.png', rotulo: "Chapéu 1" },
      { id: 'male-hat-2.png', rotulo: "Chapéu 2" },
      { id: 'male-hat-3.png', rotulo: "Chapéu 3" },
      { id: 'male-hat-4.png', rotulo: "Chapéu 4" },
      { id: 'male-hat-5.png', rotulo: "Chapéu 5" },
      { id: 'male-hat-6.png', rotulo: "Chapéu 6" },
      { id: 'male-hat-7.png', rotulo: "Chapéu 7" },
      { id: 'male-hat-8.png', rotulo: "Chapéu 8" },
      { id: 'male-hat-9.png', rotulo: "Chapéu 9" },
      { id: 'male-hat-10.png', rotulo: "Chapéu 10" },
      { id: 'male-mining-helmet.png', rotulo: "Elmo de mineiro" },
      { id: 'male-orange-cap.png', rotulo: "Boné laranja" },
      { id: 'male-purple-cap.png', rotulo: "Boné roxo" },
      { id: 'male-red-cap.png', rotulo: "Boné vermelho" },
      { id: 'male-santa-hat.png', rotulo: "Chapéu de papai noel" },
      { id: 'pumpkin-hat.png', rotulo: "Chapéu de abóbora" },
      { id: 'viking-helmet-with-horns.png', rotulo: "Elmo viking com chifres" },
      { id: 'viking-helmet.png', rotulo: "Elmo viking" },
    ],
    f: [
      { id: 'bunny-ears-1.png', rotulo: "Orelhas de coelho 1" },
      { id: 'bunny-ears-2.png', rotulo: "Orelhas de coelho 2" },
      { id: 'bunny-ears-3.png', rotulo: "Orelhas de coelho 3" },
      { id: 'bunny-ears-4.png', rotulo: "Orelhas de coelho 4" },
      { id: 'bunny-ears-5.png', rotulo: "Orelhas de coelho 5" },
      { id: 'farming-hat-f.png', rotulo: "Chapéu de palha" },
      { id: 'female-blue-cap.png', rotulo: "Boné azul" },
      { id: 'female-green-cap.png', rotulo: "Boné verde" },
      { id: 'female-hat-1.png', rotulo: "Chapéu 1" },
      { id: 'female-hat-2.png', rotulo: "Chapéu 2" },
      { id: 'female-hat-3.png', rotulo: "Chapéu 3" },
      { id: 'female-hat-4.png', rotulo: "Chapéu 4" },
      { id: 'female-hat-5.png', rotulo: "Chapéu 5" },
      { id: 'female-mining-helmet.png', rotulo: "Elmo de mineiro" },
      { id: 'female-orange-cap.png', rotulo: "Boné laranja" },
      { id: 'female-purple-cap.png', rotulo: "Boné roxo" },
      { id: 'female-red-cap.png', rotulo: "Boné vermelho" },
      { id: 'female-santa-hat.png', rotulo: "Chapéu de papai noel" },
      { id: 'witch-hat.png', rotulo: "Chapéu de bruxa" },
    ],
  },
  mascara: {
    m: [
      { id: 'male-bandit-scarf.png', rotulo: "Lenço de bandido" },
      { id: 'male-mask.png', rotulo: "Máscara" },
      { id: 'male-plague-mask.png', rotulo: "Máscara de peste" },
    ],
    f: [
      { id: 'female-blue-face-paint.png', rotulo: "Pintura de rosto azul" },
      { id: 'female-mask.png', rotulo: "Máscara" },
      { id: 'female-plague-mask.png', rotulo: "Máscara de peste" },
    ],
  },
  mao: {
    m: [
      { id: 'male-sword.png', rotulo: "Espada" },
      { id: 'bronze-axe.png', rotulo: "Machado de bronze" },
      { id: 'bronze-pickaxe.png', rotulo: "Picareta de bronze" },
      { id: 'bronze-sword.png', rotulo: "Espada de bronze" },
      { id: 'diamond-axe.png', rotulo: "Machado de diamante" },
      { id: 'diamond-pickaxe.png', rotulo: "Picareta de diamante" },
      { id: 'diamond-sword.png', rotulo: "Espada de diamante" },
      { id: 'golden-axe.png', rotulo: "Machado dourado" },
      { id: 'golden-pickaxe.png', rotulo: "Picareta dourada" },
      { id: 'golden-sword.png', rotulo: "Espada dourada" },
      { id: 'hoe-m.png', rotulo: "Enxada" },
      { id: 'iron-axe.png', rotulo: "Machado de ferro" },
      { id: 'iron-pickaxe.png', rotulo: "Picareta de ferro" },
      { id: 'iron-sword.png', rotulo: "Espada de ferro" },
      { id: 'stick.png', rotulo: "Graveto" },
      { id: 'wooden-axe.png', rotulo: "Machado de madeira" },
      { id: 'wooden-pickaxe.png', rotulo: "Picareta de madeira" },
      { id: 'wooden-sword.png', rotulo: "Espada de madeira" },
    ],
    f: [
      { id: 'female-sword.png', rotulo: "Espada" },
      { id: 'basket.png', rotulo: "Cesta" },
      { id: 'bronze-axe.png', rotulo: "Machado de bronze" },
      { id: 'bronze-pickaxe.png', rotulo: "Picareta de bronze" },
      { id: 'bronze-sword.png', rotulo: "Espada de bronze" },
      { id: 'diamond-axe.png', rotulo: "Machado de diamante" },
      { id: 'diamond-pickaxe.png', rotulo: "Picareta de diamante" },
      { id: 'diamond-sword.png', rotulo: "Espada de diamante" },
      { id: 'flower.png', rotulo: "Flor" },
      { id: 'golden-axe.png', rotulo: "Machado dourado" },
      { id: 'golden-pickaxe.png', rotulo: "Picareta dourada" },
      { id: 'golden-sword.png', rotulo: "Espada dourada" },
      { id: 'hoe-f.png', rotulo: "Enxada" },
      { id: 'iron-axe.png', rotulo: "Machado de ferro" },
      { id: 'iron-pickaxe.png', rotulo: "Picareta de ferro" },
      { id: 'iron-sword.png', rotulo: "Espada de ferro" },
      { id: 'stick.png', rotulo: "Graveto" },
      { id: 'wooden-axe.png', rotulo: "Machado de madeira" },
      { id: 'wooden-pickaxe.png', rotulo: "Picareta de madeira" },
      { id: 'wooden-sword.png', rotulo: "Espada de madeira" },
    ],
  },
  amarras: {
    m: [
      { id: 'male-blindfold.png', rotulo: "Venda" },
      { id: 'male-tied-up.png', rotulo: "Amarrado" },
    ],
    f: [
      { id: 'female-blindfold.png', rotulo: "Venda" },
      { id: 'female-tied-up.png', rotulo: "Amarrado" },
    ],
  },
};

/** quantas colunas tem cada atlas de miniatura, e o tamanho da célula */
export const PREVIA = { cols: 8, l: 40, a: 60 } as const;
