// ─────────────────────────────────────────────────────────
// SEMENTE — O QUE VOLTA A CRESCER
//
// Quarenta anos depois do Colapso, Barro Alto vive de uma horta que já
// não alimenta todo mundo. A anciã manda o jogador atravessar as ruínas
// até a antiga estação agrícola, atrás das sementes guardadas no cofre.
//
// A virada: o cofre está vazio, as sementes apodreceram. Mas o chão que
// ele pisou o caminho inteiro é um banco de sementes — enterradas,
// esperando luz. Não era um cofre. Era o chão.
//
// SOBRE O CONTEÚDO
// Cada encontro é um problema de quintal, resolvido olhando: água parada
// que fede, flor que abre e cai, pão que mofa no úmido e não no seco,
// clareira onde a árvore caiu. Biologia do cotidiano, sem fórmula e sem
// nome técnico antes da hora — o nome vem depois, batizando o que o
// aluno já entendeu.
// ─────────────────────────────────────────────────────────

export interface Fala {
  quem: string;
  texto: string;
}

export interface Escolha {
  label: string;
  certa: boolean;
  resultado: string;
}

export interface Encontro {
  id: string;
  /** o que a pessoa diz antes de perguntar */
  fala: Fala[];
  pergunta: string;
  escolhas: Escolha[];
  /** o que ela passa a dizer depois de resolvido */
  depois: string;
}

export interface Npc {
  id: string;
  x: number;
  y: number;
  /** qual folha de personagem usar */
  arte: string;
  olhando: 0 | 1 | 2 | 3;
  encontro?: string;
  /** conversa solta, para quem não tem desafio */
  conversa?: string[];
}

export interface Saida {
  x: number;
  y: number;
  para: string;
  destinoX: number;
  destinoY: number;
}

export interface Objeto {
  x: number;
  y: number;
  peca: string;
}

export interface Mapa {
  id: string;
  nome: string;
  chao: string[];
  objetos: Objeto[];
  npcs: Npc[];
  saidas: Saida[];
}

// ── encontros ────────────────────────────────────────────

export const ENCONTROS: Record<string, Encontro> = {
  poco: {
    id: 'poco',
    fala: [
      { quem: 'NITA', texto: 'Não bebe dessa água não, menino.' },
      {
        quem: 'NITA',
        texto:
          'Faz três semanas que ela está parada aí. Começou limpa. Hoje está esverdeada, ' +
          'com aquele cheiro de ovo velho, e tem bichinho nadando na superfície.',
      },
      {
        quem: 'NITA',
        texto:
          'O riacho lá embaixo é a mesma água, vem do mesmo lugar. Aquele você bebe e não ' +
          'acontece nada. Esse aqui derruba um homem em dois dias.',
      },
    ],
    pergunta: 'A água do poço está podre e a do riacho não. Por quê?',
    escolhas: [
      {
        label: 'Porque o poço é fundo e o fundo é sujo',
        certa: false,
        resultado:
          'Você raspa o fundo do poço e troca a água. Duas semanas depois, mesma coisa: verde, ' +
          'fedendo, com larva. O fundo não era o problema — era ficar parada. ' +
          'Nita ri: "Limpar não adianta se você não mexe."',
      },
      {
        label: 'Porque água parada perde o ar que tem dentro',
        certa: true,
        resultado:
          'Você abre um risco de terra ligando o poço ao riacho. Em poucos dias a água clareia e ' +
          'o cheiro some.\n\n' +
          'Tem ar dissolvido dentro da água, e é dele que vivem os bichos que limpam o resto. ' +
          'Água que despenca e se mistura recolhe ar o tempo todo; água parada gasta o que tinha ' +
          'e não repõe. Quando o ar acaba, quem assume são os que vivem SEM ar — e é o trabalho ' +
          'deles que faz aquele cheiro de ovo podre.\n\n' +
          'Não é sujeira que fede. É falta de ar.',
      },
    ],
    depois: 'A água corre agora. Passa a mão: está fria. Água parada é água morta, menino.',
  },

  horta: {
    id: 'horta',
    fala: [
      { quem: 'SEU DORIL', texto: 'Olha essa abobreira. Já viu coisa mais bonita?' },
      {
        quem: 'SEU DORIL',
        texto:
          'Flor amarela do tamanho da minha mão, uma atrás da outra, dois meses seguidos. ' +
          'E nem uma abóbora. Nenhuma. As flores abrem, ficam dois dias e caem inteiras.',
      },
      {
        quem: 'SEU DORIL',
        texto:
          'A terra está boa, eu rego todo dia, o sol bate a manhã inteira. Antes do Colapso meu ' +
          'avô plantava aqui e colhia carroça.',
      },
    ],
    pergunta: 'A abobreira floresce e não dá fruto. O que falta?',
    escolhas: [
      {
        label: 'Falta adubo — a planta não tem força para segurar a fruta',
        certa: false,
        resultado:
          'Você reforça o canteiro com esterco curtido. Vem MAIS flor ainda, do tamanho de um prato. ' +
          'E nenhuma abóbora.\n\n' +
          'A planta nunca esteve fraca. Ela estava fazendo a parte dela e esperando alguém aparecer.',
      },
      {
        label: 'Falta bicho — não vi uma abelha esse tempo todo aqui',
        certa: true,
        resultado:
          'Você repara: em duas horas de horta, nenhuma abelha, nenhuma mosca grande, nada. Só ' +
          'formiga no chão.\n\n' +
          'Então você faz o serviço na mão: pega o pó amarelo de uma flor com um pincel de pelo de ' +
          'cabra e passa no meio da outra. Nove dias depois há três abóboras pegando.\n\n' +
          'Flor é propaganda. A cor, o cheiro e o açúcar existem para pagar quem carrega o pó de ' +
          'uma flor até a outra. Sem esse carregador, a flor abre para ninguém.\n\n' +
          'Seu Doril fica calado um tempo. Depois: "Sumiram quando queimaram o mato do outro lado."',
      },
    ],
    depois: 'Três pegando, menino. Três! Vou plantar flor no meio da horta, pra chamar os bichos de volta.',
  },

  paiol: {
    id: 'paiol',
    fala: [
      { quem: 'VILMA', texto: 'Perdi metade do paiol esse mês. Metade.' },
      {
        quem: 'VILMA',
        texto:
          'O pão que fica no canto de baixo cria aquele veludo verde em três dias. O que fica na ' +
          'prateleira de cima, perto da telha quebrada, dura duas semanas e só resseca.',
      },
      {
        quem: 'VILMA',
        texto:
          'Mesmo pão, mesmo forno, mesmo dia. Só muda o lugar. E o canto de baixo é o mais fresco ' +
          'do paiol — eu achei que fresco fosse melhor.',
      },
    ],
    pergunta: 'Por que o pão de baixo mofa e o de cima não?',
    escolhas: [
      {
        label: 'O canto de baixo está mais frio, e o frio estraga o pão',
        certa: false,
        resultado:
          'Você sobe tudo para o canto quente, perto do forno. O pão mofa mais rápido ainda, e ' +
          'agora azeda junto.\n\n' +
          'Não era o frio. Frio de verdade — de gelo — atrasa o mofo. O que o canto de baixo tem ' +
          'a mais não é temperatura: é água no ar.',
      },
      {
        label: 'O canto de baixo é úmido, e o mofo precisa de água',
        certa: true,
        resultado:
          'Você abre a telha, deixa o vento entrar e passa o pão para a prateleira alta. O mofo para.\n\n' +
          'Mofo é um ser vivo, e todo ser vivo precisa de água para trabalhar. No úmido ele come, ' +
          'cresce e se espalha; no seco ele fica parado, esperando.\n\n' +
          'É por isso que carne salgada e peixe seco atravessam o ano: o sal e o sol tiram a água ' +
          'que o mofo usaria. Ninguém matou o bicho — só tiraram a bebida dele.\n\n' +
          'Vilma anota tudo num pedaço de saco.',
      },
    ],
    depois: 'Alto e ventilado. Escrevi na parede pra ninguém esquecer.',
  },

  clareira: {
    id: 'clareira',
    fala: [
      { quem: 'TEO', texto: 'Ó, moço. Repara nesse pedaço aqui.' },
      {
        quem: 'TEO',
        texto:
          'A árvore grande caiu no temporal do ano passado. Antes disso aqui era escuro e limpo, ' +
          'só folha seca no chão, nada crescia.',
      },
      {
        quem: 'TEO',
        texto:
          'Um ano depois está desse jeito: capim na altura do meu peito, três tipos de flor, ' +
          'aquele arbusto de fruta vermelha. Ninguém plantou nada. Ninguém regou.',
      },
    ],
    pergunta: 'Ninguém plantou. De onde veio tudo isso?',
    escolhas: [
      {
        label: 'O vento trouxe as sementes depois que a árvore caiu',
        certa: false,
        resultado:
          'Vento traz semente, é verdade. Mas em um ano ele não traria capim, flor E arbusto de ' +
          'fruta, todos brotando na mesma semana, exatamente no buraco de luz.\n\n' +
          'Teo aponta para fora da clareira: "Ali também bate vento. Ali não nasceu nada."',
      },
      {
        label: 'As sementes já estavam no chão, esperando luz',
        certa: true,
        resultado:
          'Você cava um punhado de terra na sombra, longe da clareira, e espalha num caixote ao sol. ' +
          'Em três semanas o caixote está verde. Ninguém plantou aquilo. Já estava lá.\n\n' +
          'O chão de mata guarda semente enterrada por anos, viva e parada. Falta luz. Enquanto a ' +
          'árvore grande estava de pé, ela tomava toda a luz para si e ninguém debaixo dela ' +
          'conseguia crescer. Ela caiu, abriu o buraco — e o chão descarregou o que estava guardando.\n\n' +
          'Teo: "Então a mata é um paiol." É exatamente isso.',
      },
    ],
    depois: 'Um paiol embaixo do pé da gente. Vou contar pra minha mãe.',
  },
};

export const ORDEM = ['poco', 'horta', 'paiol', 'clareira'];

// ── mapas ────────────────────────────────────────────────
// . grama   , grama com tufo   ; grama com pedrisco   t terra batida
// = piso de pedra   # parede (barra passagem)

export const MAPAS: Record<string, Mapa> = {
  povoado: {
    id: 'povoado',
    nome: 'BARRO ALTO',
    chao: [
      '##############################',
      '##############################',
      '##############################',
      '##############################',
      '##############################',
      '######,,,............,,,######',
      '######...............,,,######',
      '######...............,,,######',
      '######...............,,,######',
      '######......ttttt....,,,######',
      '######......ttttt.....,,######',
      '######......ttttt.....,,######',
      '######.......tt........,######',
      '######..tttttttttttttt..######',
      '######.......tt,,,,,,...######',
      '######.......tt,,,,,,...######',
      '######.......tt,,,,,,...######',
      '######.......tt,,,,,,...######',
      '######.......tt,,,,,,,..######',
      '######.......tt,,,,,,,,,######',
      '######..tttttttttttttt,,######',
      '######.......tt,,,,,,,,,######',
      '######.......tt...,,,,,,######',
      '######.......tt..hhhhh,,######',
      '######.......tt..hhhhh,,######',
      '######.......tt..hhhhh,,######',
      '######.......tt..hhhhh,,######',
      '######.......tt..hhhhh,,######',
      '######.......tt.........######',
      '#############tt###############',
      '#############tt###############',
      '#############tt###############',
      '#############tt###############',
      '#############tt###############',
    ],
    objetos: [
      { x: 6, y: 5, peca: 'casa' },
      { x: 17, y: 5, peca: 'casa' },
      { x: 7, y: 21, peca: 'casa' },
      { x: 16, y: 22, peca: 'cercaH' },
      { x: 16, y: 28, peca: 'cercaH' },
      { x: 17, y: 22, peca: 'cercaH' },
      { x: 17, y: 28, peca: 'cercaH' },
      { x: 18, y: 28, peca: 'cercaH' },
      { x: 19, y: 22, peca: 'cercaH' },
      { x: 19, y: 28, peca: 'cercaH' },
      { x: 20, y: 22, peca: 'cercaH' },
      { x: 20, y: 28, peca: 'cercaH' },
      { x: 21, y: 22, peca: 'cercaH' },
      { x: 21, y: 28, peca: 'cercaH' },
      { x: 22, y: 22, peca: 'cercaH' },
      { x: 22, y: 28, peca: 'cercaH' },
      { x: 16, y: 23, peca: 'cercaV' },
      { x: 22, y: 23, peca: 'cercaV' },
      { x: 16, y: 24, peca: 'cercaV' },
      { x: 22, y: 24, peca: 'cercaV' },
      { x: 16, y: 25, peca: 'cercaV' },
      { x: 22, y: 25, peca: 'cercaV' },
      { x: 16, y: 26, peca: 'cercaV' },
      { x: 22, y: 26, peca: 'cercaV' },
      { x: 16, y: 27, peca: 'cercaV' },
      { x: 22, y: 27, peca: 'cercaV' },
      { x: 17, y: 24, peca: 'cenoura' },
      { x: 17, y: 25, peca: 'mudaSolo' },
      { x: 17, y: 26, peca: 'trigo' },
      { x: 17, y: 27, peca: 'broto' },
      { x: 18, y: 24, peca: 'mudaSolo' },
      { x: 18, y: 25, peca: 'trigo' },
      { x: 18, y: 26, peca: 'broto' },
      { x: 18, y: 27, peca: 'cenoura' },
      { x: 19, y: 24, peca: 'trigo' },
      { x: 19, y: 25, peca: 'broto' },
      { x: 19, y: 26, peca: 'cenoura' },
      { x: 19, y: 27, peca: 'mudaSolo' },
      { x: 20, y: 24, peca: 'broto' },
      { x: 20, y: 25, peca: 'cenoura' },
      { x: 20, y: 26, peca: 'mudaSolo' },
      { x: 20, y: 27, peca: 'trigo' },
      { x: 21, y: 24, peca: 'cenoura' },
      { x: 21, y: 25, peca: 'mudaSolo' },
      { x: 21, y: 26, peca: 'trigo' },
      { x: 21, y: 27, peca: 'broto' },
      { x: 11, y: 15, peca: 'poste' },
      { x: 15, y: 23, peca: 'poste' },
      { x: 16, y: 14, peca: 'tocoSeco' },
      { x: 18, y: 14, peca: 'pedras' },
      { x: 16, y: 15, peca: 'bau' },
      { x: 11, y: 19, peca: 'pedreira' },
      { x: 20, y: 17, peca: 'pedreira2' },
      { x: 17, y: 23, peca: 'tora' },
      { x: 15, y: 8, peca: 'placa' },
      { x: 19, y: 14, peca: 'tora' },
      { x: 10, y: 30, peca: 'pedreira3' },
      { x: 10, y: 15, peca: 'galinha' },
      { x: 9, y: 18, peca: 'galinha' },
      { x: 20, y: 19, peca: 'ovelha' },
      { x: 8, y: 15, peca: 'canteiro1' },
      { x: 8, y: 16, peca: 'canteiro2' },
      { x: 9, y: 15, peca: 'canteiro3' },
      { x: 22, y: 13, peca: 'arvoreMedia' },
      { x: 7, y: 17, peca: 'arvorePeq' },
      { x: 19, y: 29, peca: 'arvoreMedia' },
      { x: 2, y: 0, peca: 'arvore' },
      { x: 14, y: 0, peca: 'arvore' },
      { x: 25, y: 0, peca: 'arvore' },
      { x: 1, y: 4, peca: 'arvore' },
      { x: 23, y: 4, peca: 'arvore' },
      { x: 0, y: 6, peca: 'arvore' },
      { x: 26, y: 6, peca: 'arvoreSeca' },
      { x: 2, y: 10, peca: 'arvore' },
      { x: 25, y: 10, peca: 'arvore' },
      { x: 2, y: 12, peca: 'arvoreSeca' },
      { x: 24, y: 13, peca: 'arvoreSeca' },
      { x: 1, y: 15, peca: 'arvore' },
      { x: 26, y: 15, peca: 'arvoreMata' },
      { x: 1, y: 19, peca: 'arvore' },
      { x: 25, y: 18, peca: 'arvore' },
      { x: 2, y: 21, peca: 'arvoreSeca' },
      { x: 25, y: 21, peca: 'arvore' },
      { x: 2, y: 25, peca: 'arvore' },
      { x: 26, y: 25, peca: 'arvore' },
      { x: 2, y: 28, peca: 'arvoreMata' },
      { x: 7, y: 28, peca: 'arvoreMata' },
      { x: 15, y: 28, peca: 'arvoreSeca' },
      { x: 21, y: 27, peca: 'arvoreMata' },
      { x: 26, y: 28, peca: 'arvore' },
      { x: 0, y: 0, peca: 'arvorePeqSeca' },
      { x: 2, y: 0, peca: 'arvorePeq' },
      { x: 4, y: 0, peca: 'arvorePeqSeca' },
      { x: 6, y: 0, peca: 'arvorePeq' },
      { x: 9, y: 0, peca: 'arvorePeqSeca' },
      { x: 11, y: 0, peca: 'arvorePeq' },
      { x: 13, y: 0, peca: 'arvorePeqSeca' },
      { x: 15, y: 0, peca: 'arvorePeq' },
      { x: 17, y: 0, peca: 'arvorePeq' },
      { x: 19, y: 0, peca: 'arvorePeqSeca' },
      { x: 23, y: 0, peca: 'arvorePeq' },
      { x: 26, y: 0, peca: 'arvorePeqSeca' },
      { x: 28, y: 0, peca: 'arvorePeqSeca' },
      { x: 0, y: 2, peca: 'arvorePeq' },
      { x: 6, y: 2, peca: 'arvorePeq' },
      { x: 9, y: 2, peca: 'arvorePeqSeca' },
      { x: 12, y: 2, peca: 'arvorePeq' },
      { x: 20, y: 2, peca: 'arvorePeq' },
      { x: 22, y: 2, peca: 'arvorePeq' },
      { x: 18, y: 3, peca: 'arvorePeq' },
      { x: 0, y: 5, peca: 'arvorePeq' },
      { x: 2, y: 5, peca: 'arvorePeqSeca' },
      { x: 24, y: 5, peca: 'arvorePeqSeca' },
      { x: 27, y: 7, peca: 'arvorePeqSeca' },
      { x: 4, y: 9, peca: 'arvorePeq' },
      { x: 24, y: 9, peca: 'arvorePeqSeca' },
      { x: 0, y: 11, peca: 'arvorePeq' },
      { x: 3, y: 11, peca: 'arvorePeq' },
      { x: 24, y: 11, peca: 'arvorePeq' },
      { x: 27, y: 11, peca: 'arvorePeq' },
      { x: 0, y: 14, peca: 'arvorePeqSeca' },
      { x: 28, y: 15, peca: 'arvorePeqSeca' },
      { x: 24, y: 18, peca: 'arvorePeq' },
      { x: 3, y: 20, peca: 'arvorePeqSeca' },
      { x: 0, y: 24, peca: 'arvorePeqSeca' },
      { x: 0, y: 26, peca: 'arvorePeq' },
      { x: 2, y: 26, peca: 'arvorePeq' },
      { x: 24, y: 26, peca: 'arvorePeq' },
      { x: 26, y: 26, peca: 'arvorePeqSeca' },
      { x: 28, y: 26, peca: 'arvorePeq' },
      { x: 0, y: 28, peca: 'arvorePeq' },
      { x: 6, y: 29, peca: 'arvorePeq' },
      { x: 8, y: 29, peca: 'arvorePeq' },
      { x: 11, y: 29, peca: 'arvorePeq' },
      { x: 15, y: 29, peca: 'arvorePeqSeca' },
      { x: 20, y: 32, peca: 'arvorePeqSeca' },
      { x: 22, y: 32, peca: 'arvorePeq' },
      { x: 2, y: 0, peca: 'tufo3' },
      { x: 3, y: 0, peca: 'tufo' },
      { x: 4, y: 0, peca: 'tufo2' },
      { x: 5, y: 0, peca: 'tufo3' },
      { x: 7, y: 0, peca: 'tufo2' },
      { x: 9, y: 0, peca: 'tufo3' },
      { x: 13, y: 0, peca: 'tufo3' },
      { x: 14, y: 0, peca: 'tufo3' },
      { x: 15, y: 0, peca: 'capimAlto' },
      { x: 18, y: 0, peca: 'tufo' },
      { x: 20, y: 0, peca: 'capimAlto' },
      { x: 25, y: 0, peca: 'tufo' },
      { x: 27, y: 0, peca: 'moitaRasteira' },
      { x: 28, y: 0, peca: 'tufo3' },
      { x: 8, y: 1, peca: 'capimAlto' },
      { x: 3, y: 2, peca: 'capimAlto' },
      { x: 5, y: 2, peca: 'capimAlto' },
      { x: 6, y: 2, peca: 'moitaRasteira' },
      { x: 8, y: 2, peca: 'tufo' },
      { x: 9, y: 2, peca: 'tufo3' },
      { x: 11, y: 2, peca: 'capimAlto' },
      { x: 15, y: 2, peca: 'moitaRasteira' },
      { x: 19, y: 2, peca: 'moitaRasteira' },
      { x: 22, y: 2, peca: 'tufo2' },
      { x: 25, y: 2, peca: 'moitaRasteira' },
      { x: 26, y: 2, peca: 'tufo2' },
      { x: 28, y: 2, peca: 'tufo2' },
      { x: 8, y: 3, peca: 'capimAlto' },
      { x: 11, y: 3, peca: 'tufo' },
      { x: 18, y: 3, peca: 'capimAlto' },
      { x: 6, y: 4, peca: 'tufo' },
      { x: 9, y: 4, peca: 'tufo' },
      { x: 10, y: 4, peca: 'tufo' },
      { x: 11, y: 4, peca: 'tufo2' },
      { x: 12, y: 4, peca: 'moitaRasteira' },
      { x: 20, y: 4, peca: 'tufo3' },
      { x: 21, y: 4, peca: 'tufo2' },
      { x: 22, y: 4, peca: 'tufo' },
      { x: 23, y: 4, peca: 'capimAlto' },
      { x: 24, y: 4, peca: 'tufo3' },
      { x: 3, y: 5, peca: 'tufo' },
      { x: 25, y: 5, peca: 'moitaRasteira' },
      { x: 27, y: 5, peca: 'moitaRasteira' },
      { x: 29, y: 5, peca: 'capimAlto' },
      { x: 5, y: 6, peca: 'capimAlto' },
      { x: 29, y: 6, peca: 'capimAlto' },
      { x: 5, y: 7, peca: 'capimAlto' },
      { x: 27, y: 7, peca: 'capimAlto' },
      { x: 28, y: 7, peca: 'tufo3' },
      { x: 29, y: 7, peca: 'tufo3' },
      { x: 1, y: 11, peca: 'tufo3' },
      { x: 2, y: 11, peca: 'moitaRasteira' },
      { x: 3, y: 11, peca: 'moitaRasteira' },
      { x: 4, y: 11, peca: 'tufo' },
      { x: 25, y: 11, peca: 'tufo' },
      { x: 26, y: 11, peca: 'capimAlto' },
      { x: 28, y: 11, peca: 'tufo3' },
      { x: 2, y: 12, peca: 'moitaRasteira' },
      { x: 5, y: 12, peca: 'capimAlto' },
      { x: 26, y: 12, peca: 'tufo2' },
      { x: 1, y: 13, peca: 'tufo3' },
      { x: 29, y: 13, peca: 'capimAlto' },
      { x: 0, y: 14, peca: 'tufo2' },
      { x: 1, y: 14, peca: 'capimAlto' },
      { x: 24, y: 15, peca: 'moitaRasteira' },
      { x: 25, y: 15, peca: 'capimAlto' },
      { x: 27, y: 15, peca: 'tufo3' },
      { x: 28, y: 15, peca: 'tufo3' },
      { x: 1, y: 17, peca: 'tufo' },
      { x: 2, y: 17, peca: 'tufo3' },
      { x: 3, y: 17, peca: 'tufo2' },
      { x: 4, y: 17, peca: 'tufo3' },
      { x: 5, y: 17, peca: 'moitaRasteira' },
      { x: 28, y: 17, peca: 'moitaRasteira' },
      { x: 29, y: 17, peca: 'tufo' },
      { x: 0, y: 18, peca: 'tufo' },
      { x: 5, y: 19, peca: 'tufo3' },
      { x: 0, y: 20, peca: 'tufo' },
      { x: 3, y: 20, peca: 'tufo3' },
      { x: 4, y: 20, peca: 'tufo3' },
      { x: 26, y: 20, peca: 'tufo' },
      { x: 28, y: 20, peca: 'tufo' },
      { x: 29, y: 20, peca: 'capimAlto' },
      { x: 1, y: 21, peca: 'moitaRasteira' },
      { x: 5, y: 21, peca: 'tufo' },
      { x: 29, y: 21, peca: 'moitaRasteira' },
      { x: 0, y: 22, peca: 'tufo2' },
      { x: 0, y: 23, peca: 'moitaRasteira' },
      { x: 5, y: 23, peca: 'tufo' },
      { x: 24, y: 23, peca: 'moitaRasteira' },
      { x: 28, y: 23, peca: 'capimAlto' },
      { x: 29, y: 23, peca: 'capimAlto' },
      { x: 29, y: 24, peca: 'tufo' },
      { x: 0, y: 26, peca: 'capimAlto' },
      { x: 1, y: 26, peca: 'tufo2' },
      { x: 2, y: 26, peca: 'tufo3' },
      { x: 4, y: 26, peca: 'tufo3' },
      { x: 24, y: 26, peca: 'tufo3' },
      { x: 25, y: 26, peca: 'tufo2' },
      { x: 27, y: 26, peca: 'tufo2' },
      { x: 29, y: 26, peca: 'tufo' },
      { x: 5, y: 27, peca: 'tufo2' },
      { x: 0, y: 28, peca: 'moitaRasteira' },
      { x: 1, y: 28, peca: 'moitaRasteira' },
      { x: 7, y: 29, peca: 'tufo3' },
      { x: 8, y: 29, peca: 'tufo' },
      { x: 9, y: 29, peca: 'tufo3' },
      { x: 11, y: 29, peca: 'tufo' },
      { x: 15, y: 29, peca: 'tufo' },
      { x: 16, y: 29, peca: 'moitaRasteira' },
      { x: 21, y: 29, peca: 'tufo3' },
      { x: 23, y: 29, peca: 'tufo3' },
      { x: 24, y: 29, peca: 'moitaRasteira' },
      { x: 25, y: 29, peca: 'moitaRasteira' },
      { x: 0, y: 30, peca: 'tufo2' },
      { x: 17, y: 30, peca: 'capimAlto' },
      { x: 18, y: 30, peca: 'tufo3' },
      { x: 26, y: 30, peca: 'tufo2' },
      { x: 0, y: 31, peca: 'capimAlto' },
      { x: 12, y: 31, peca: 'moitaRasteira' },
      { x: 25, y: 31, peca: 'moitaRasteira' },
      { x: 0, y: 32, peca: 'capimAlto' },
      { x: 1, y: 32, peca: 'moitaRasteira' },
      { x: 20, y: 32, peca: 'tufo' },
      { x: 25, y: 32, peca: 'tufo2' },
      { x: 0, y: 33, peca: 'capimAlto' },
      { x: 2, y: 33, peca: 'tufo3' },
      { x: 4, y: 33, peca: 'tufo' },
      { x: 5, y: 33, peca: 'tufo3' },
      { x: 7, y: 33, peca: 'tufo3' },
      { x: 8, y: 33, peca: 'tufo2' },
      { x: 9, y: 33, peca: 'tufo3' },
      { x: 11, y: 33, peca: 'capimAlto' },
      { x: 17, y: 33, peca: 'tufo2' },
      { x: 18, y: 33, peca: 'tufo' },
      { x: 19, y: 33, peca: 'capimAlto' },
      { x: 24, y: 33, peca: 'tufo2' },
      { x: 27, y: 33, peca: 'capimAlto' },
      { x: 29, y: 33, peca: 'moitaRasteira' },
      { x: 16, y: 5, peca: 'tufo' },
      { x: 23, y: 5, peca: 'capimAlto' },
      { x: 15, y: 6, peca: 'capimAlto' },
      { x: 12, y: 7, peca: 'pedrinhas' },
      { x: 16, y: 7, peca: 'moitaRasteira' },
      { x: 12, y: 8, peca: 'tufo2' },
      { x: 13, y: 8, peca: 'florAmarela' },
      { x: 7, y: 14, peca: 'florLaranja' },
      { x: 8, y: 14, peca: 'moitaRasteira' },
      { x: 12, y: 14, peca: 'florAmarela' },
      { x: 17, y: 14, peca: 'tufo' },
      { x: 15, y: 15, peca: 'pedrinhas' },
      { x: 10, y: 16, peca: 'tufo3' },
      { x: 15, y: 16, peca: 'tufo' },
      { x: 19, y: 16, peca: 'capimAlto' },
      { x: 20, y: 16, peca: 'capimAlto' },
      { x: 22, y: 16, peca: 'tufo2' },
      { x: 23, y: 16, peca: 'florAmarela' },
      { x: 10, y: 17, peca: 'moitaRasteira' },
      { x: 15, y: 17, peca: 'florBranca' },
      { x: 17, y: 17, peca: 'capimAlto' },
      { x: 6, y: 18, peca: 'tufo3' },
      { x: 22, y: 18, peca: 'tufo' },
      { x: 10, y: 19, peca: 'moitaRasteira' },
      { x: 18, y: 19, peca: 'tufo' },
      { x: 21, y: 19, peca: 'tufo3' },
      { x: 7, y: 20, peca: 'florBranca' },
      { x: 23, y: 20, peca: 'florLaranja' },
      { x: 23, y: 21, peca: 'moitaRasteira' },
      { x: 15, y: 22, peca: 'tufo' },
      { x: 23, y: 22, peca: 'florBranca' },
      { x: 23, y: 26, peca: 'cogumelo' },
      { x: 6, y: 27, peca: 'tufo3' },
      { x: 15, y: 11, peca: 'pedrinhas' },
      { x: 13, y: 14, peca: 'pedras' },
    ],
    npcs: [
      {
        id: 'anciana', x: 15, y: 12, arte: 'anciana', olhando: 0,
        conversa: [
          'Barro Alto tem cento e onze bocas e uma horta que dá para setenta.',
          'Antes do Colapso havia uma estação agrícola trilha abaixo. Diziam que guardavam ' +
            'semente de tudo num cofre frio, para o caso de um dia faltar.',
          'Um dia faltou. Desce a trilha do sul, menino. Fala com quem encontrar no caminho — ' +
            'quem ficou vivo aprendeu a olhar.',
        ],
      },
      {
        id: 'nita', x: 12, y: 17, arte: 'nita', olhando: 3,
        encontro: 'poco',
      },
      {
        id: 'vilma', x: 10, y: 14, arte: 'vilma', olhando: 1,
        encontro: 'paiol',
      },
      {
        id: 'doril', x: 17, y: 21, arte: 'doril', olhando: 1,
        encontro: 'horta',
      },
    ],
    saidas: [
      { x: 13, y: 33, para: 'trilha', destinoX: 14, destinoY: 1 },
    ],
  },

  trilha: {
    id: 'trilha',
    nome: 'TRILHA DO SUL',
    chao: [
      '##############ttt#############',
      '##############ttt#############',
      '##############ttt#############',
      '##############ttt#############',
      '##############tt##############',
      '######,,,,,,,,tt,,,,,,..######',
      '######,,,,,,,,tt,,,,,,,,######',
      '######,,,,,,,,tt,,,,,,,,######',
      '######,,,,,,,tt,,,,,,,,,######',
      '######,,,,,,,ttt,,,,,,,,######',
      '######,,,,,,,tt,,,,,,,,,######',
      '######,,,,,,,tt,,,,,,,,,######',
      '######,,,,,,,tt,,,,,,,,,######',
      '######,,,,,,,tt,,,,,,,,,######',
      '######,,,,,,,,tt,,..,,,,######',
      '######,,,,,,,,tt......,,######',
      '######,,,,,,,,ttt......,######',
      '######,,,,,,,,tt.......,######',
      '######,,,,,,,..tt......,######',
      '######,,,,,,,..tt......,######',
      '######,,,,,,...ttt.....,######',
      '######.........tt......,######',
      '######........tttttt....######',
      '######.........~~.tt....######',
      '######......~~~~~~tt~~~~######',
      '######~~~~~~~~~.~.tt~~~.######',
      '######.~~~.~~.....ttt...######',
      '######.~~~~~.......ttt..######',
      '######.~~~~~.......tt...######',
      '######.~~~~~.......tt...######',
      '######~~~~~~.......tt...######',
      '######~~~~~~......tt....######',
      '######.~~~~~......tt....######',
      '######,~~~~,,,,,,,tt,...######',
      '######,,,~~,,,,,,,ttt,..######',
      '##################tt##########',
      '#################ttt##########',
      '#################ttt##########',
      '#################ttt##########',
      '#################ttt##########',
    ],
    objetos: [
      { x: 18, y: 23, peca: 'ponteV' },
      { x: 9, y: 7, peca: 'arvoreSeca' },
      { x: 19, y: 9, peca: 'arvoreSeca' },
      { x: 9, y: 13, peca: 'arvoreSeca' },
      { x: 20, y: 15, peca: 'arvoreSeca' },
      { x: 8, y: 19, peca: 'arvoreSeca' },
      { x: 21, y: 29, peca: 'arvoreSeca' },
      { x: 7, y: 4, peca: 'arvoreMediaSeca' },
      { x: 21, y: 20, peca: 'arvoreMediaSeca' },
      { x: 11, y: 34, peca: 'arvorePeq' },
      { x: 21, y: 35, peca: 'arvorePeqSeca' },
      { x: 16, y: 12, peca: 'pedreira' },
      { x: 12, y: 20, peca: 'pedreira2' },
      { x: 21, y: 26, peca: 'pedreira3' },
      { x: 11, y: 12, peca: 'tora' },
      { x: 15, y: 28, peca: 'tora' },
      { x: 8, y: 16, peca: 'tocoSeco' },
      { x: 17, y: 18, peca: 'tocoSeco' },
      { x: 13, y: 30, peca: 'pedras' },
      { x: 23, y: 10, peca: 'cristal' },
      { x: 20, y: 33, peca: 'tocoSeco' },
      { x: 21, y: 34, peca: 'tora' },
      { x: 14, y: 31, peca: 'broto' },
      { x: 16, y: 31, peca: 'broto' },
      { x: 13, y: 33, peca: 'broto' },
      { x: 15, y: 34, peca: 'broto' },
      { x: 12, y: 32, peca: 'broto' },
      { x: 16, y: 35, peca: 'broto' },
      { x: 14, y: 35, peca: 'broto' },
      { x: 0, y: 1, peca: 'arvore' },
      { x: 15, y: 0, peca: 'arvoreSeca' },
      { x: 23, y: 0, peca: 'arvoreSeca' },
      { x: 1, y: 4, peca: 'arvore' },
      { x: 26, y: 3, peca: 'arvoreMata' },
      { x: 1, y: 7, peca: 'arvoreMata' },
      { x: 24, y: 6, peca: 'arvore' },
      { x: 0, y: 9, peca: 'arvoreMata' },
      { x: 23, y: 10, peca: 'arvore' },
      { x: 2, y: 12, peca: 'arvoreMata' },
      { x: 25, y: 12, peca: 'arvore' },
      { x: 0, y: 16, peca: 'arvoreMata' },
      { x: 24, y: 16, peca: 'arvoreMata' },
      { x: 1, y: 18, peca: 'arvoreSeca' },
      { x: 23, y: 19, peca: 'arvoreSeca' },
      { x: 1, y: 21, peca: 'arvore' },
      { x: 22, y: 21, peca: 'arvoreSeca' },
      { x: 2, y: 24, peca: 'arvoreSeca' },
      { x: 26, y: 24, peca: 'arvore' },
      { x: 1, y: 28, peca: 'arvoreMata' },
      { x: 25, y: 27, peca: 'arvoreMata' },
      { x: 0, y: 31, peca: 'arvoreMata' },
      { x: 26, y: 31, peca: 'arvoreSeca' },
      { x: 1, y: 33, peca: 'arvore' },
      { x: 8, y: 33, peca: 'arvoreMata' },
      { x: 21, y: 34, peca: 'arvoreMata' },
      { x: 26, y: 34, peca: 'arvoreSeca' },
      { x: 0, y: 0, peca: 'arvorePeqSeca' },
      { x: 2, y: 0, peca: 'arvorePeqSeca' },
      { x: 4, y: 0, peca: 'arvorePeqSeca' },
      { x: 6, y: 0, peca: 'arvorePeq' },
      { x: 9, y: 0, peca: 'arvorePeqSeca' },
      { x: 11, y: 0, peca: 'arvorePeq' },
      { x: 17, y: 0, peca: 'arvorePeqSeca' },
      { x: 19, y: 0, peca: 'arvorePeqSeca' },
      { x: 23, y: 0, peca: 'arvorePeqSeca' },
      { x: 26, y: 0, peca: 'arvorePeqSeca' },
      { x: 28, y: 0, peca: 'arvorePeqSeca' },
      { x: 0, y: 2, peca: 'arvorePeq' },
      { x: 2, y: 2, peca: 'arvorePeqSeca' },
      { x: 4, y: 2, peca: 'arvorePeq' },
      { x: 6, y: 2, peca: 'arvorePeqSeca' },
      { x: 9, y: 2, peca: 'arvorePeqSeca' },
      { x: 12, y: 2, peca: 'arvorePeqSeca' },
      { x: 20, y: 2, peca: 'arvorePeq' },
      { x: 27, y: 2, peca: 'arvorePeq' },
      { x: 4, y: 4, peca: 'arvorePeqSeca' },
      { x: 24, y: 5, peca: 'arvorePeqSeca' },
      { x: 24, y: 7, peca: 'arvorePeqSeca' },
      { x: 28, y: 9, peca: 'arvorePeqSeca' },
      { x: 24, y: 11, peca: 'arvorePeqSeca' },
      { x: 27, y: 11, peca: 'arvorePeqSeca' },
      { x: 0, y: 14, peca: 'arvorePeqSeca' },
      { x: 0, y: 17, peca: 'arvorePeqSeca' },
      { x: 2, y: 17, peca: 'arvorePeq' },
      { x: 4, y: 17, peca: 'arvorePeqSeca' },
      { x: 26, y: 17, peca: 'arvorePeqSeca' },
      { x: 28, y: 17, peca: 'arvorePeqSeca' },
      { x: 28, y: 20, peca: 'arvorePeq' },
      { x: 28, y: 23, peca: 'arvorePeqSeca' },
      { x: 26, y: 24, peca: 'arvorePeqSeca' },
      { x: 0, y: 26, peca: 'arvorePeqSeca' },
      { x: 24, y: 26, peca: 'arvorePeqSeca' },
      { x: 0, y: 28, peca: 'arvorePeqSeca' },
      { x: 2, y: 29, peca: 'arvorePeqSeca' },
      { x: 25, y: 32, peca: 'arvorePeqSeca' },
      { x: 28, y: 32, peca: 'arvorePeqSeca' },
      { x: 4, y: 34, peca: 'arvorePeqSeca' },
      { x: 6, y: 35, peca: 'arvorePeq' },
      { x: 23, y: 35, peca: 'arvorePeq' },
      { x: 12, y: 36, peca: 'arvorePeqSeca' },
      { x: 14, y: 36, peca: 'arvorePeq' },
      { x: 5, y: 37, peca: 'arvorePeq' },
      { x: 2, y: 38, peca: 'arvorePeqSeca' },
      { x: 7, y: 38, peca: 'arvorePeqSeca' },
      { x: 9, y: 38, peca: 'arvorePeqSeca' },
      { x: 12, y: 38, peca: 'arvorePeqSeca' },
      { x: 15, y: 38, peca: 'arvorePeq' },
      { x: 2, y: 0, peca: 'pedrinhas' },
      { x: 3, y: 0, peca: 'tufo' },
      { x: 4, y: 0, peca: 'trigoSeco' },
      { x: 5, y: 0, peca: 'pedrinhas' },
      { x: 7, y: 0, peca: 'trigoSeco' },
      { x: 9, y: 0, peca: 'pedrinhas' },
      { x: 18, y: 0, peca: 'tufo' },
      { x: 20, y: 0, peca: 'capimAlto' },
      { x: 25, y: 0, peca: 'tufo' },
      { x: 27, y: 0, peca: 'moitaRasteira' },
      { x: 28, y: 0, peca: 'pedrinhas' },
      { x: 8, y: 1, peca: 'capimAlto' },
      { x: 3, y: 2, peca: 'capimAlto' },
      { x: 5, y: 2, peca: 'capimAlto' },
      { x: 6, y: 2, peca: 'moitaRasteira' },
      { x: 8, y: 2, peca: 'tufo' },
      { x: 9, y: 2, peca: 'pedrinhas' },
      { x: 11, y: 2, peca: 'capimAlto' },
      { x: 19, y: 2, peca: 'moitaRasteira' },
      { x: 22, y: 2, peca: 'trigoSeco' },
      { x: 25, y: 2, peca: 'moitaRasteira' },
      { x: 26, y: 2, peca: 'trigoSeco' },
      { x: 28, y: 2, peca: 'trigoSeco' },
      { x: 8, y: 3, peca: 'capimAlto' },
      { x: 11, y: 3, peca: 'tufo' },
      { x: 22, y: 3, peca: 'pedrinhas' },
      { x: 6, y: 4, peca: 'tufo' },
      { x: 9, y: 4, peca: 'tufo' },
      { x: 10, y: 4, peca: 'tufo' },
      { x: 11, y: 4, peca: 'trigoSeco' },
      { x: 12, y: 4, peca: 'moitaRasteira' },
      { x: 19, y: 4, peca: 'pedrinhas' },
      { x: 20, y: 4, peca: 'pedrinhas' },
      { x: 21, y: 4, peca: 'trigoSeco' },
      { x: 22, y: 4, peca: 'tufo' },
      { x: 28, y: 4, peca: 'trigoSeco' },
      { x: 25, y: 5, peca: 'moitaRasteira' },
      { x: 27, y: 5, peca: 'moitaRasteira' },
      { x: 29, y: 5, peca: 'capimAlto' },
      { x: 1, y: 6, peca: 'pedrinhas' },
      { x: 2, y: 6, peca: 'pedrinhas' },
      { x: 3, y: 6, peca: 'pedrinhas' },
      { x: 5, y: 6, peca: 'capimAlto' },
      { x: 5, y: 7, peca: 'capimAlto' },
      { x: 24, y: 7, peca: 'trigoSeco' },
      { x: 27, y: 8, peca: 'tufo' },
      { x: 0, y: 9, peca: 'pedrinhas' },
      { x: 1, y: 9, peca: 'tufo' },
      { x: 0, y: 10, peca: 'capimAlto' },
      { x: 5, y: 10, peca: 'capimAlto' },
      { x: 25, y: 11, peca: 'tufo' },
      { x: 26, y: 11, peca: 'capimAlto' },
      { x: 28, y: 11, peca: 'pedrinhas' },
      { x: 5, y: 12, peca: 'capimAlto' },
      { x: 26, y: 12, peca: 'trigoSeco' },
      { x: 28, y: 13, peca: 'tufo' },
      { x: 29, y: 13, peca: 'capimAlto' },
      { x: 0, y: 14, peca: 'trigoSeco' },
      { x: 1, y: 14, peca: 'capimAlto' },
      { x: 3, y: 14, peca: 'trigoSeco' },
      { x: 4, y: 14, peca: 'trigoSeco' },
      { x: 5, y: 14, peca: 'capimAlto' },
      { x: 27, y: 14, peca: 'tufo' },
      { x: 28, y: 14, peca: 'pedrinhas' },
      { x: 24, y: 15, peca: 'moitaRasteira' },
      { x: 29, y: 16, peca: 'tufo' },
      { x: 1, y: 17, peca: 'tufo' },
      { x: 2, y: 17, peca: 'pedrinhas' },
      { x: 3, y: 17, peca: 'trigoSeco' },
      { x: 4, y: 17, peca: 'pedrinhas' },
      { x: 5, y: 17, peca: 'moitaRasteira' },
      { x: 25, y: 17, peca: 'capimAlto' },
      { x: 26, y: 17, peca: 'capimAlto' },
      { x: 28, y: 17, peca: 'moitaRasteira' },
      { x: 29, y: 17, peca: 'tufo' },
      { x: 5, y: 19, peca: 'pedrinhas' },
      { x: 28, y: 19, peca: 'tufo' },
      { x: 4, y: 20, peca: 'pedrinhas' },
      { x: 28, y: 20, peca: 'tufo' },
      { x: 29, y: 20, peca: 'capimAlto' },
      { x: 5, y: 21, peca: 'tufo' },
      { x: 25, y: 21, peca: 'trigoSeco' },
      { x: 27, y: 21, peca: 'trigoSeco' },
      { x: 0, y: 22, peca: 'trigoSeco' },
      { x: 0, y: 23, peca: 'moitaRasteira' },
      { x: 1, y: 23, peca: 'capimAlto' },
      { x: 2, y: 23, peca: 'trigoSeco' },
      { x: 5, y: 23, peca: 'tufo' },
      { x: 28, y: 23, peca: 'capimAlto' },
      { x: 29, y: 23, peca: 'capimAlto' },
      { x: 26, y: 24, peca: 'tufo' },
      { x: 27, y: 24, peca: 'capimAlto' },
      { x: 5, y: 25, peca: 'moitaRasteira' },
      { x: 0, y: 26, peca: 'capimAlto' },
      { x: 1, y: 26, peca: 'trigoSeco' },
      { x: 2, y: 26, peca: 'pedrinhas' },
      { x: 4, y: 26, peca: 'pedrinhas' },
      { x: 24, y: 26, peca: 'pedrinhas' },
      { x: 25, y: 26, peca: 'trigoSeco' },
      { x: 27, y: 26, peca: 'trigoSeco' },
      { x: 29, y: 26, peca: 'tufo' },
      { x: 0, y: 28, peca: 'moitaRasteira' },
      { x: 1, y: 28, peca: 'moitaRasteira' },
      { x: 2, y: 29, peca: 'trigoSeco' },
      { x: 3, y: 29, peca: 'tufo' },
      { x: 5, y: 29, peca: 'tufo' },
      { x: 25, y: 29, peca: 'moitaRasteira' },
      { x: 28, y: 29, peca: 'pedrinhas' },
      { x: 0, y: 30, peca: 'trigoSeco' },
      { x: 0, y: 31, peca: 'capimAlto' },
      { x: 29, y: 31, peca: 'tufo' },
      { x: 0, y: 32, peca: 'capimAlto' },
      { x: 25, y: 32, peca: 'trigoSeco' },
      { x: 28, y: 32, peca: 'moitaRasteira' },
      { x: 0, y: 33, peca: 'capimAlto' },
      { x: 2, y: 33, peca: 'pedrinhas' },
      { x: 4, y: 33, peca: 'tufo' },
      { x: 5, y: 33, peca: 'pedrinhas' },
      { x: 27, y: 33, peca: 'capimAlto' },
      { x: 4, y: 34, peca: 'capimAlto' },
      { x: 5, y: 34, peca: 'capimAlto' },
      { x: 24, y: 34, peca: 'trigoSeco' },
      { x: 25, y: 34, peca: 'pedrinhas' },
      { x: 8, y: 35, peca: 'trigoSeco' },
      { x: 9, y: 35, peca: 'tufo' },
      { x: 10, y: 35, peca: 'pedrinhas' },
      { x: 13, y: 35, peca: 'moitaRasteira' },
      { x: 15, y: 35, peca: 'trigoSeco' },
      { x: 20, y: 35, peca: 'pedrinhas' },
      { x: 23, y: 35, peca: 'tufo' },
      { x: 24, y: 35, peca: 'moitaRasteira' },
      { x: 25, y: 35, peca: 'pedrinhas' },
      { x: 0, y: 36, peca: 'moitaRasteira' },
      { x: 5, y: 36, peca: 'tufo' },
      { x: 12, y: 36, peca: 'tufo' },
      { x: 13, y: 36, peca: 'moitaRasteira' },
      { x: 14, y: 36, peca: 'pedrinhas' },
      { x: 15, y: 36, peca: 'trigoSeco' },
      { x: 25, y: 36, peca: 'capimAlto' },
      { x: 26, y: 36, peca: 'trigoSeco' },
      { x: 27, y: 36, peca: 'capimAlto' },
      { x: 5, y: 37, peca: 'tufo' },
      { x: 7, y: 37, peca: 'capimAlto' },
      { x: 16, y: 37, peca: 'capimAlto' },
      { x: 20, y: 37, peca: 'trigoSeco' },
      { x: 0, y: 38, peca: 'tufo' },
      { x: 3, y: 38, peca: 'pedrinhas' },
      { x: 4, y: 38, peca: 'capimAlto' },
      { x: 8, y: 38, peca: 'capimAlto' },
      { x: 9, y: 38, peca: 'capimAlto' },
      { x: 10, y: 38, peca: 'capimAlto' },
      { x: 12, y: 38, peca: 'moitaRasteira' },
      { x: 14, y: 38, peca: 'tufo' },
      { x: 15, y: 38, peca: 'moitaRasteira' },
      { x: 16, y: 38, peca: 'capimAlto' },
      { x: 25, y: 38, peca: 'tufo' },
      { x: 1, y: 39, peca: 'pedrinhas' },
      { x: 5, y: 39, peca: 'capimAlto' },
      { x: 6, y: 39, peca: 'pedrinhas' },
      { x: 11, y: 39, peca: 'capimAlto' },
      { x: 14, y: 39, peca: 'moitaRasteira' },
      { x: 20, y: 39, peca: 'pedrinhas' },
      { x: 23, y: 39, peca: 'trigoSeco' },
      { x: 24, y: 39, peca: 'trigoSeco' },
      { x: 25, y: 39, peca: 'capimAlto' },
      { x: 26, y: 39, peca: 'moitaRasteira' },
      { x: 27, y: 39, peca: 'trigoSeco' },
      { x: 29, y: 39, peca: 'pedrinhas' },
      { x: 11, y: 5, peca: 'capimAlto' },
      { x: 13, y: 5, peca: 'trigoSeco' },
      { x: 18, y: 5, peca: 'tufo' },
      { x: 23, y: 5, peca: 'moitaRasteira' },
      { x: 11, y: 6, peca: 'trigoSeco' },
      { x: 21, y: 6, peca: 'pedras' },
      { x: 23, y: 6, peca: 'pedrinhas' },
      { x: 16, y: 7, peca: 'trigoSeco' },
      { x: 19, y: 7, peca: 'pedras' },
      { x: 20, y: 7, peca: 'tufo3' },
      { x: 21, y: 7, peca: 'pedrinhas' },
      { x: 7, y: 8, peca: 'capimAlto' },
      { x: 20, y: 8, peca: 'tufo' },
      { x: 22, y: 8, peca: 'tufo3' },
      { x: 18, y: 9, peca: 'tufo2' },
      { x: 15, y: 10, peca: 'tufo3' },
      { x: 6, y: 11, peca: 'tufo' },
      { x: 8, y: 11, peca: 'tufo2' },
      { x: 17, y: 11, peca: 'pedras' },
      { x: 23, y: 11, peca: 'tufo3' },
      { x: 7, y: 12, peca: 'pedrinhas' },
      { x: 8, y: 13, peca: 'tufo2' },
      { x: 17, y: 13, peca: 'tufo2' },
      { x: 7, y: 14, peca: 'tufo2' },
      { x: 13, y: 14, peca: 'pedrinhas' },
      { x: 20, y: 14, peca: 'trigoSeco' },
      { x: 17, y: 15, peca: 'pedras' },
      { x: 18, y: 16, peca: 'pedras' },
      { x: 6, y: 19, peca: 'trigoSeco' },
      { x: 12, y: 19, peca: 'moitaRasteira' },
      { x: 14, y: 19, peca: 'pedras' },
      { x: 17, y: 19, peca: 'trigoSeco' },
      { x: 13, y: 20, peca: 'tufo3' },
      { x: 14, y: 20, peca: 'trigoSeco' },
      { x: 6, y: 21, peca: 'capimAlto' },
      { x: 12, y: 21, peca: 'tufo' },
      { x: 18, y: 21, peca: 'pedrinhas' },
      { x: 20, y: 21, peca: 'moitaRasteira' },
      { x: 20, y: 22, peca: 'tufo3' },
      { x: 17, y: 23, peca: 'tufo2' },
      { x: 15, y: 25, peca: 'tufo2' },
      { x: 17, y: 25, peca: 'pedras' },
      { x: 6, y: 26, peca: 'tufo2' },
      { x: 10, y: 26, peca: 'tufo2' },
      { x: 13, y: 27, peca: 'pedras' },
      { x: 15, y: 27, peca: 'moitaRasteira' },
      { x: 16, y: 27, peca: 'moitaRasteira' },
      { x: 23, y: 27, peca: 'moitaRasteira' },
      { x: 21, y: 28, peca: 'moitaRasteira' },
      { x: 12, y: 29, peca: 'pedrinhas' },
      { x: 15, y: 29, peca: 'pedrinhas' },
      { x: 16, y: 29, peca: 'tufo2' },
      { x: 12, y: 30, peca: 'trigoSeco' },
      { x: 18, y: 30, peca: 'trigoSeco' },
      { x: 17, y: 31, peca: 'pedrinhas' },
      { x: 6, y: 32, peca: 'tufo3' },
      { x: 14, y: 32, peca: 'trigoSeco' },
      { x: 6, y: 33, peca: 'capimAlto' },
      { x: 12, y: 33, peca: 'tufo2' },
      { x: 8, y: 34, peca: 'pedras' },
      { x: 17, y: 34, peca: 'tufo3' },
      { x: 14, y: 5, peca: 'pedrinhas' },
      { x: 19, y: 29, peca: 'pedrinhas' },
      { x: 20, y: 30, peca: 'pedrinhas' },
    ],
    npcs: [
      {
        id: 'andarilho', x: 13, y: 16, arte: 'andarilho', olhando: 3,
        conversa: [
          'A estação fica no fim da trilha, do lado da boca de pedra. Você não erra.',
          'Já fui lá. Não vou voltar. O que você procura não está lá dentro.',
        ],
      },
      {
        id: 'teo', x: 17, y: 33, arte: 'teo', olhando: 3,
        encontro: 'clareira',
      },
    ],
    saidas: [
      { x: 14, y: 0, para: 'povoado', destinoX: 13, destinoY: 32 },
      { x: 18, y: 39, para: 'estacao', destinoX: 11, destinoY: 18 },
    ],
  },

  estacao: {
    id: 'estacao',
    nome: 'ESTAÇÃO AGRÍCOLA',
    chao: [
      '########################',
      '########################',
      '########################',
      '########################',
      '####================####',
      '####================####',
      '####================####',
      '####================####',
      '####================####',
      '####================####',
      '####================####',
      '####================####',
      '####================####',
      '####================####',
      '####================####',
      '####================####',
      '###########tt###########',
      '###########tt###########',
      '###########tt###########',
      '###########tt###########',
    ],
    objetos: [
      { x: 11, y: 5, peca: 'bau' },
      { x: 4, y: 4, peca: 'pedreira2' },
      { x: 6, y: 4, peca: 'pedreira' },
      { x: 8, y: 4, peca: 'pedreira3' },
      { x: 10, y: 4, peca: 'pedreira2' },
      { x: 12, y: 4, peca: 'pedreira' },
      { x: 14, y: 4, peca: 'pedreira3' },
      { x: 16, y: 4, peca: 'pedreira2' },
      { x: 18, y: 4, peca: 'pedreira' },
      { x: 4, y: 5, peca: 'pedreira' },
      { x: 19, y: 5, peca: 'pedreira2' },
      { x: 4, y: 7, peca: 'pedreira3' },
      { x: 19, y: 7, peca: 'pedreira' },
      { x: 4, y: 9, peca: 'pedreira2' },
      { x: 19, y: 9, peca: 'pedreira3' },
      { x: 4, y: 11, peca: 'pedreira' },
      { x: 19, y: 11, peca: 'pedreira2' },
      { x: 4, y: 13, peca: 'pedreira3' },
      { x: 19, y: 13, peca: 'pedreira' },
      { x: 4, y: 15, peca: 'pedreira2' },
      { x: 6, y: 15, peca: 'pedreira2' },
      { x: 8, y: 15, peca: 'pedreira2' },
      { x: 14, y: 15, peca: 'pedreira3' },
      { x: 16, y: 15, peca: 'pedreira3' },
      { x: 18, y: 15, peca: 'pedreira3' },
      { x: 7, y: 6, peca: 'tocoSeco' },
      { x: 16, y: 7, peca: 'pedras' },
      { x: 6, y: 12, peca: 'pedrinhas' },
      { x: 15, y: 12, peca: 'pedras' },
      { x: 9, y: 9, peca: 'pedrinhas' },
      { x: 8, y: 7, peca: 'broto' },
      { x: 13, y: 8, peca: 'broto' },
      { x: 7, y: 10, peca: 'broto' },
      { x: 14, y: 10, peca: 'broto' },
      { x: 10, y: 12, peca: 'broto' },
      { x: 12, y: 6, peca: 'broto' },
      { x: 16, y: 13, peca: 'broto' },
      { x: 6, y: 8, peca: 'broto' },
      { x: 17, y: 11, peca: 'broto' },
      { x: 9, y: 13, peca: 'broto' },
      { x: 13, y: 13, peca: 'broto' },
      { x: 11, y: 9, peca: 'broto' },
      { x: 5, y: 10, peca: 'capimAlto' },
      { x: 18, y: 8, peca: 'tufo' },
      { x: 12, y: 11, peca: 'tufo2' },
      { x: 8, y: 14, peca: 'moitaRasteira' },
      { x: 15, y: 5, peca: 'trigoSeco' },
      { x: 20, y: 0, peca: 'arvoreSeca' },
      { x: 0, y: 3, peca: 'arvoreMata' },
      { x: 20, y: 7, peca: 'arvoreSeca' },
      { x: 1, y: 13, peca: 'arvoreMata' },
      { x: 5, y: 13, peca: 'arvoreMata' },
      { x: 13, y: 13, peca: 'arvoreSeca' },
      { x: 1, y: 15, peca: 'arvoreSeca' },
      { x: 16, y: 15, peca: 'arvoreSeca' },
      { x: 0, y: 0, peca: 'arvorePeq' },
      { x: 2, y: 0, peca: 'arvorePeqSeca' },
      { x: 4, y: 0, peca: 'arvorePeq' },
      { x: 6, y: 0, peca: 'arvorePeqSeca' },
      { x: 9, y: 0, peca: 'arvorePeq' },
      { x: 11, y: 0, peca: 'arvorePeq' },
      { x: 13, y: 0, peca: 'arvorePeq' },
      { x: 15, y: 0, peca: 'arvorePeq' },
      { x: 17, y: 0, peca: 'arvorePeqSeca' },
      { x: 19, y: 0, peca: 'arvorePeq' },
      { x: 22, y: 1, peca: 'arvorePeq' },
      { x: 0, y: 2, peca: 'arvorePeqSeca' },
      { x: 2, y: 2, peca: 'arvorePeqSeca' },
      { x: 4, y: 2, peca: 'arvorePeq' },
      { x: 6, y: 2, peca: 'arvorePeqSeca' },
      { x: 9, y: 2, peca: 'arvorePeq' },
      { x: 12, y: 2, peca: 'arvorePeqSeca' },
      { x: 16, y: 2, peca: 'arvorePeq' },
      { x: 1, y: 4, peca: 'arvorePeq' },
      { x: 20, y: 5, peca: 'arvorePeqSeca' },
      { x: 22, y: 5, peca: 'arvorePeqSeca' },
      { x: 20, y: 7, peca: 'arvorePeq' },
      { x: 22, y: 7, peca: 'arvorePeq' },
      { x: 0, y: 8, peca: 'arvorePeq' },
      { x: 0, y: 10, peca: 'arvorePeqSeca' },
      { x: 0, y: 12, peca: 'arvorePeqSeca' },
      { x: 20, y: 12, peca: 'arvorePeqSeca' },
      { x: 22, y: 12, peca: 'arvorePeqSeca' },
      { x: 2, y: 13, peca: 'arvorePeq' },
      { x: 0, y: 14, peca: 'arvorePeq' },
      { x: 20, y: 14, peca: 'arvorePeqSeca' },
      { x: 22, y: 15, peca: 'arvorePeqSeca' },
      { x: 18, y: 16, peca: 'arvorePeq' },
      { x: 20, y: 17, peca: 'arvorePeq' },
      { x: 6, y: 18, peca: 'arvorePeqSeca' },
      { x: 8, y: 18, peca: 'arvorePeq' },
      { x: 14, y: 18, peca: 'arvorePeqSeca' },
      { x: 2, y: 0, peca: 'pedrinhas' },
      { x: 3, y: 0, peca: 'tufo' },
      { x: 4, y: 0, peca: 'trigoSeco' },
      { x: 5, y: 0, peca: 'pedrinhas' },
      { x: 7, y: 0, peca: 'trigoSeco' },
      { x: 9, y: 0, peca: 'pedrinhas' },
      { x: 13, y: 0, peca: 'pedrinhas' },
      { x: 14, y: 0, peca: 'pedrinhas' },
      { x: 15, y: 0, peca: 'capimAlto' },
      { x: 18, y: 0, peca: 'tufo' },
      { x: 20, y: 0, peca: 'capimAlto' },
      { x: 8, y: 1, peca: 'capimAlto' },
      { x: 23, y: 1, peca: 'tufo' },
      { x: 3, y: 2, peca: 'capimAlto' },
      { x: 5, y: 2, peca: 'capimAlto' },
      { x: 6, y: 2, peca: 'moitaRasteira' },
      { x: 8, y: 2, peca: 'tufo' },
      { x: 9, y: 2, peca: 'pedrinhas' },
      { x: 11, y: 2, peca: 'capimAlto' },
      { x: 15, y: 2, peca: 'moitaRasteira' },
      { x: 19, y: 2, peca: 'moitaRasteira' },
      { x: 8, y: 3, peca: 'capimAlto' },
      { x: 11, y: 3, peca: 'tufo' },
      { x: 14, y: 3, peca: 'pedrinhas' },
      { x: 15, y: 3, peca: 'tufo' },
      { x: 18, y: 3, peca: 'capimAlto' },
      { x: 3, y: 5, peca: 'tufo' },
      { x: 20, y: 5, peca: 'moitaRasteira' },
      { x: 21, y: 5, peca: 'trigoSeco' },
      { x: 20, y: 7, peca: 'tufo' },
      { x: 21, y: 7, peca: 'moitaRasteira' },
      { x: 23, y: 7, peca: 'trigoSeco' },
      { x: 3, y: 8, peca: 'trigoSeco' },
      { x: 22, y: 9, peca: 'capimAlto' },
      { x: 0, y: 10, peca: 'capimAlto' },
      { x: 2, y: 10, peca: 'trigoSeco' },
      { x: 2, y: 11, peca: 'moitaRasteira' },
      { x: 3, y: 11, peca: 'moitaRasteira' },
      { x: 2, y: 12, peca: 'moitaRasteira' },
      { x: 3, y: 12, peca: 'capimAlto' },
      { x: 20, y: 12, peca: 'capimAlto' },
      { x: 22, y: 12, peca: 'moitaRasteira' },
      { x: 2, y: 13, peca: 'capimAlto' },
      { x: 3, y: 13, peca: 'trigoSeco' },
      { x: 0, y: 14, peca: 'trigoSeco' },
      { x: 1, y: 14, peca: 'capimAlto' },
      { x: 22, y: 14, peca: 'moitaRasteira' },
      { x: 23, y: 14, peca: 'tufo' },
      { x: 2, y: 15, peca: 'pedrinhas' },
      { x: 23, y: 15, peca: 'moitaRasteira' },
      { x: 9, y: 16, peca: 'moitaRasteira' },
      { x: 10, y: 16, peca: 'pedrinhas' },
      { x: 17, y: 16, peca: 'tufo' },
      { x: 18, y: 16, peca: 'tufo' },
      { x: 19, y: 16, peca: 'tufo' },
      { x: 20, y: 16, peca: 'pedrinhas' },
      { x: 17, y: 17, peca: 'trigoSeco' },
      { x: 22, y: 17, peca: 'capimAlto' },
      { x: 23, y: 17, peca: 'moitaRasteira' },
      { x: 0, y: 18, peca: 'tufo' },
      { x: 8, y: 18, peca: 'pedrinhas' },
      { x: 9, y: 18, peca: 'tufo' },
      { x: 14, y: 18, peca: 'capimAlto' },
      { x: 23, y: 18, peca: 'capimAlto' },
      { x: 5, y: 19, peca: 'pedrinhas' },
      { x: 21, y: 19, peca: 'pedrinhas' },
      { x: 22, y: 19, peca: 'trigoSeco' },
    ],
    npcs: [

    ],
    saidas: [
      { x: 11, y: 19, para: 'trilha', destinoX: 18, destinoY: 38 },
    ],
  },
};

export const MAPA_INICIAL = 'povoado';
export const INICIO = { x: 13, y: 20, olhando: 1 as const };
